username: "Wano CI/CD Bot"
icon_url: "https://wanoafrica.com/wp-content/uploads/2025/04/Logo.png" # Replace with your logo URL!
pretext: "🚀 Deployment workflow started by *{{actor}}* on branch *{{branch}}*"
title: "Wano Africa Backend Deployment"
title_link: "{{workflowRunUrl}}"

text: |
  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
  {{#if description}}_{{description}}_{{/if}}

  *Commit*: <https://github.com/{{repositoryName}}/commit/{{sha}}|`{{truncate sha 7}}`> - _by {{actor}}_

  {{#if jobSteps}}
  *Steps:*
  {{#each jobSteps}}
    - {{icon this.outcome}} *{{@key}}*: {{this.outcome}}
  {{/each}}
  {{/if}}

fallback: "[Wano] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}"

fields:
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Job Name
    value: "{{jobName}}"
    short: true
  - title: Git Ref
    value: "{{ref}} ({{refType}})"
    short: true
  - title: Actor
    value: "{{actor}}"
    short: true
  - title: Job Status
    value: "{{jobStatus}}"
    short: true
  - title: Run ID
    value: "<{{workflowRunUrl}}|{{runId}}>"
    short: true

footer: "<{{repositoryUrl}}|{{repositoryName}}> | Run #{{runNumber}}"

colors:
  success: "#27ae60"
  failure: "#c0392b"
  cancelled: "#f1c40f"
  default: "#95a5a6"

icons:
  success: ":white_check_mark:"
  failure: ":x:"
  cancelled: ":pause_button:"
  skipped: ":fast_forward:"
  default: ":question:"
